logging:
  level:
    org.springframework: trace
  structured:
    format:
      console: ecs
spring:
  application:
    name: Bet Service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always