logging:
  level:
    org.springframework: trace
spring:
  application:
    name: Bet Service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://betting-auth-server
